### PR TITLE
CP-1193 Release w_flux 2.1.0

### PR DESCRIPTION
**Pull request by jayudey-wf**
JIRA: https://jira.webfilings.com/browse/CP-1193

JIRA and PR's included in this release: 

 CP-1226  - cleanup old tooling, w_flux  - https://github.com/Workiva/w_flux/pull/52

 CP-1415  - Allow use of react-dart 0.9.0, w_flux  - https://github.com/Workiva/w_flux/pull/53

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/2.0.0...CP-1193_release_2.1.0

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by dustinlessard-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
