### PR TITLE
CP-1056 Release w_flux 1.1.0

### PR DESCRIPTION
**Pull request by jayudey-wf**
JIRA: https://jira.webfilings.com/browse/CP-1056

JIRA and PR's included in this release: 

 CP-1060  - Update CHANGELOG.md, w_flux  - https://github.com/Workiva/w_flux/pull/42
 CP-1152  - Add clearListeners method to Action  - https://github.com/Workiva/w_flux/pull/44
 REF-278  - Add RedrawScheduler to wFlux  - https://github.com/Workiva/w_flux/pull/45
 CP-1168  - fix strong mode analysis errors / warnings, w_flux  - https://github.com/Workiva/w_flux/pull/46

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/1.0.1...CP-1056_release_1.1.0

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
