### PR TITLE
CPLAT-6767 Bump build dep ranges to fix build in master

### PR DESCRIPTION
**Pull request by smaifullerton-wk**
## Motivation
  
Building in master is currently erroring with: 
```
[SEVERE] build_web_compilers:ddc on package:package_resolver/package_resolver.dartdevc.module:
Error compiling dartdevc module:package_resolver|lib/package_resolver.ddc.js

[error] The imported library ''current_isolate_resolver_stub.dart'' can't have a part-of directive. (package:package_resolver/src/package_resolver.dart, line 12, col 8)
[error] The imported library ''utils_isolate_stub.dart'' can't have a part-of directive. (package:package_resolver/src/utils.dart, line 15, col 8)

Please fix all errors before compiling (warnings are okay).
```

## Changes
  
Expand build_* dep range to get latest with fix.

## Review
_[See CONTRIBUTING.md][contributing-review-types] for more details on review types (+1 / QA +1 / +10) and code review process._

  

Please review: 

### QA Checklist
- [ ] CI passes

## Merge Checklist
While we perform many automated checks before auto-merging, some manual checks are needed:
- [ ] A Client Platform member has reviewed these changes
- [ ] There are no unaddressed comments _- this check can be automated if reviewers use the "Request Changes" feature_
- [ ] _For release PRs -_ Version metadata in Rosie comment is correct

[contributing-review-types]: https://github.com/Workiva/w_flux/blob/master/CONTRIBUTING.md#review-types
[contributing-manual-testing]: https://github.com/Workiva/w_flux/blob/master/CONTRIBUTING.md#manual-testing-criteria

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by georgelesica-wf** [comment]
+1

**Comment by todbachman-wf** [comment]
+10, assuming the builds pass.

**Comment by evanweible-wf** [comment]
QA +1
- [x] Manually verified the CI steps on Dart 2.4.0
  - Tests pass
  - Analysis pass
  - No formatting changes needed

@Workiva/release-management-p

**Comment by smaifullerton-wk** [comment]
@Workiva/release-management-p

**Pull request merged**
