### PR TITLE
CHART-1760 make w_flux compatible with strong mode

### PR DESCRIPTION
**Pull request by kylemcmorrow-wf**
Allow w_flux to be compatible with strong mode

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1 thanks @kylemcmorrow-wf!

**Comment by evanweible-wf** [comment]
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction (derived from conversation with Kyle)
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - passing CI with strong analysis enabled
- [ ] Unit test created/updated
- [ ] All unit tests pass 

Merging into master.

**Pull request merged**
