### PR TITLE
WP-4449 Remove rate limit dependency.

### PR DESCRIPTION
**Pull request by aaronstgeorge-wf**
Problem
--------

`rate_limit` is not strong mode compliant.

Solution
--------

Remove the dependency.

Potential Regressions
--------

None, the dependency appears unused.

Tests
--------
No changes.

QA / +10
--------

- [ ] CI should pass

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by maxwellpeterson-wf** [comment]
QA +1
- [x] Minimum dependency bump only
- [x] Dev +1's
- [x] CI passes
- [x] Dependency scan clean

@Workiva/release-management-pp

**Comment by dustinlessard-wf** [comment]
(nice)!

**Comment by rmconsole-wf** [comment]
+1 from RM

**Pull request merged**
