### PR TITLE
WP-5242 Widen react-dart range to include memory leak fix in 4.0.0

### PR DESCRIPTION
**Pull request by greglittlefield-wf**
## Dependency, config, and/or RM change callouts
Widen react-dart dependency to include 4.0.0.

## Problem
react-dart 4.0.0 includes improvements to Dart component instance management that help avoid certain memory leaks. See more info here: https://github.com/cleandart/react-dart/pull/127.

While this release contains breaking changes, those breakages are limited to internals that should be smoothed over by over_react, and should not affect the majority of consumers.

## Solution
Widen react-dart version range to include 4.0.0.

Once this range has been widened throughout the Workiva's dependency tree, everyone should get 4.0.0 for free.

## Test Overview (+10 Instructions)
- [ ] Verify that `pub get` still resolves properly in the build, and react-dart 4.0.0 is pulled in
- [ ] Verify that tests pass

## Semantic Versioning
**Patch**
- [x] This change does not affect the public API

## Areas of Regression
React component rendering/testing

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
<details>
<summary>Number of Findings: 0</summary>

</details>

**Comment by jayudey-wf** [comment]
QA +1

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
  - verified that travis ran with react 4.0.0
  - ran example and verified that they were working as expected
- [ ] Security review (if required)
- [ ] Unit tests created/updated - N/A dep bump
- [ ] All unit tests pass
- [ ] Rosie has run and reports properly the release the ticket will be included in

Merging into master.

**Comment by jayudey-wf** [comment]
@Workiva/release-management-pp

**Comment by rmconsole-wf** [comment]
+1 from RM

**Pull request merged**
