### PR TITLE
CP-1055 Allow react 0.8.0 in dependency range, w_flux

### LINKED ISSUE #39: Allow react 0.8.0 in dependency range
This shouldn't cause any issues for w_flux that I am aware of.

### PR DESCRIPTION
**Pull request by maxwellpeterson-wf**
## Issue
Fixes #39 

## Changes
**Source:**
- Update `react` dependency range to include 0.8.x

## Areas of Regression
- None

## Testing
- CI passes

@trentgrover-wf 
@evanweible-wf 
@dustinlessard-wf 
FYI @jayudey-wf

### CODE REVIEW

**Comment by trentgrover-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - passing CI
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Pull request merged**
