### PR TITLE
CP-951 Release w_flux 1.0.1

### PR DESCRIPTION
**Pull request by jayudey-wf**
JIRA: https://jira.webfilings.com/browse/CP-951

JIRA and PR's included in this release: 

 CP-956  - Add badges to README. w_flux  - https://github.com/Workiva/w_flux/pull/37
 CP-1017  - Fix usage of expect-async in action tests.  - https://github.com/Workiva/w_flux/pull/38
 CP-1055  - Allow react 0.8.0 in dependency range, w_flux  - https://github.com/Workiva/w_flux/pull/40

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/1.0.0...CP-951_release_1.0.1

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
