### PR TITLE
WP-3352 Release w_flux 2.7.0

### PR DESCRIPTION
**Pull request by rm-astro-wf**
Pulls Included in Release:
* [WP-3660 : added docs.yml](https://github.com/Workiva/w_flux/pull/82)
* [HY-4736 Expose trigger stream on store](https://github.com/Workiva/w_flux/pull/84)

Requested by: @evanweible-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/2.6.1...version-bump-w_flux-2-7-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_flux/compare/2.6.1...2.7.0

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by evanweible-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
QA +1

- [x] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Comment by patkujawa-wf** [comment]
This version still isn't on pub

**Pull request merged**
