### PR TITLE
CP-1060 Update CHANGELOG.md, w_flux

### PR DESCRIPTION
**Pull request by maxwellpeterson-wf**
## Issue
Changelog is out of date

## Testing
- CI passes
- Docs only change

@trentgrover-wf 
@evanweible-wf 
@dustinlessard-wf 
FYI @jayudey-wf

### CODE REVIEW

**Comment by trentgrover-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA +1, doc change only

Merging into master

**Pull request merged**
