### PR TITLE
CP-2036 Release w_flux 2.4.0

### PR DESCRIPTION
**Pull request by jayudey-wf**
JIRA: https://jira.webfilings.com/browse/CP-2036

Releases that need to go out at the same time (if any): 

JIRA and PR's included in this release: 

======= w_flux 2.4.0 items =======

 CP-2381  - Bump react-dart version constraint to ^3.0.0  - https://github.com/Workiva/w_flux/pull/65

======= end =======

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/2.3.1...CP-2036_release_2.4.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_flux/compare/2.3.1...2.4.0

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by srinivasdhanwada-wf** [comment]
+1

**Comment by sebastianmalysa-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
