### PR TITLE
CP-2631 Release w_flux 2.6.0

### PR DESCRIPTION
**Pull request by rmconsole3-wf**
Pulls Included in Release:
* [CP-2596 Store implements Disposable](https://github.com/Workiva/w_flux/pull/75)
* [CP-2944 Fix intermittent failures, add basic smithy.yaml, add sleep to Travis CI startup](https://github.com/Workiva/w_flux/pull/78)

Requested by: @charliekump-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/2.5.0...version-bump-w_flux-2-6-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_flux/compare/2.5.0...2.6.0

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by evanweible-wf** [comment]
+1

**Comment by dustinlessard-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
