### PR TITLE
CP-937 Setup Travis CI and codecov.io reporting, w_flux

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
#27 Travis CI
#28 Codecov.io
Dart 1.12 introduces a new `.packages` file that should be ignored

## Changes
- Updated dart_dev dep to use the pub version
- Removed `smithy.yml`
- Submitted ticket to have smithy turned off for this repo: https://jira.atl.workiva.net/secure/Dashboard.jspa
- Added `travis.yml` to run..
  - static analysis
  - dart formatter check
  - tests
  - coverage
  - coverage reporting
- Added `.packages` to gitignore

## Areas of Regression
- CI builds

## Testing
- Travis CI passes
- Coverage is reported to codecov.io and codecov.io checks pass
- Ignore failing smithy checks

## Code Review
@trentgrover-wf
@maxwellpeterson-wf 
@dustinlessard-wf
@jayudey-wf

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - travis build successfully and coverage is accurately reported
 - failing smithy is expected
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Comment by jayudey-wf** [comment]
@rosie run_merge_script

**Pull request merged**
