### PR TITLE
CP-2936 Adding smithy

### PR DESCRIPTION
**Pull request by jayudey-wf**
## Issue
- We needed to add a smithy.yaml for release management to more easily track dependencies.

## Changes
**Source:**
- Included smithy.yaml

**Tests:**
- n/a

## Areas of Regression
- passing CI's

## Testing
- passing CI

## Code Review
@maxwellpeterson-wf
@evanweible-wf
@dustinlessard-wf
@sebastianmalysa-wf

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by dustinlessard-wf** [comment]
+1

**Comment by ekweible** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by dustinlessard-wf** [comment]
Oh noes!

**Comment by evanweible-wf** [comment]
Should be able to close this in in favor of #78

**Pull request closed without merging**
