### PR TITLE
HY-4736 Expose trigger stream on store

### PR DESCRIPTION
**Pull request by seanburke-wf**
### Purpose
Allow more flexible access to a `Store`'s trigger stream, particularly for testing.

### Solution
Add a `stream` getter to the `Store` class.

### Semantic Versioning
**MINOR**. Adds new API to the `Store` class.

### Testing
- CI passes

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by patkujawa-wf** [comment]
+1 CR. This is great, because it prevents having to do things like in these three duplicate tests: https://github.com/Workiva/graph_app/pull/2835/commits/d1e79db7a3a59b7dd26648bdd0c7e949500c4c7d#diff-2a9c7a1e46d75b1156f5a4e489be71c2

**Comment by georgelesica-wf** [comment]
We just need to bump the Dart version in the Travis config. We should also increase the minimum SDK in the pubspec since there's no way this will work with 1.9.0 or whatever the lower bound is right now.

**Comment by georgelesica-wf** [comment]
+1 lgtm

**Comment by stephenbush-wf** [comment]
+10 CI passed!

**Comment by maxwellpeterson-wf** [comment]
+1
Any objections @trentgrover-wf @evanweible-wf ?

**Comment by georgelesica-wf** [comment]
## Release Notes

The `Store` now exposes its stream of triggers through the `stream` getter.

**Comment by trentgrover-wf** [comment]
do we think anyone will want to really use it for anything besides testing?  if not, we could use the `@visibleForTesting` annotation so that it's not really considered part of the public API

**Comment by todbachman-wf** [comment]
I vote for adding the `@visibleForTesting` annotation. I can only imagine this would be useful for testing.

**Comment by seanburke-wf** [comment]
Addressed.

**Comment by todbachman-wf** [comment]
+1

**Comment by patkujawa-wf** [comment]
Doesn't `@visibleForTesting` imply protected, so it would only be accessible from this module without warning? We should verify.

**Comment by evanweible-wf** [comment]
+1

**Comment by patkujawa-wf** [comment]
@evanweible-wf can this merge?

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
QA +1
- [x] Testing instruction
- [x] Dev +1's
- [x] Dev/QA +10 with detail of what was tested
- [x] Unit tests created/updated 
- [x] All unit tests pass

Merging into master.

**Pull request merged**
