### PR TITLE
CP-2958 Release w_flux 2.6.1

### PR DESCRIPTION
**Pull request by rm-astro-wf**
Pulls Included in Release:
* [CP-3349 Relax Action handler return type](https://github.com/Workiva/w_flux/pull/80)

Requested by: @evanweible-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/2.6.0...version-bump-w_flux-2-6-1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_flux/compare/2.6.0...2.6.1

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by evanweible-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
@jayudey-wf ready for you

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
