### PR TITLE
CP-794 Release w_flux 1.0.0

### PR DESCRIPTION
**Pull request by jayudey-wf**
JIRA: https://jira.webfilings.com/browse/CP-794

JIRA and PR's included in this release: 

 CP-818  - add docs and examples, w_flux  - https://github.com/Workiva/w_flux/pull/23
 CP-846  - Add CHANGELOG, w_flux  - https://github.com/Workiva/w_flux/pull/26
 CP-853  - Use dart_dev for tooling, w_flux  - https://github.com/Workiva/w_flux/pull/24
 CP-855  - Add license, copy license to all src files, w_flux  - https://github.com/Workiva/w_flux/pull/25
 CP-857  - Prepare pubspec.yaml for OSS  - https://github.com/Workiva/w_flux/pull/31
 CP-854  - Fix image link in README, w_flux  - https://github.com/Workiva/w_flux/pull/30
 CP-937  - Setup Travis CI and codecov.io reporting, w_flux  - https://github.com/Workiva/w_flux/pull/33
 CP-942  - Document FluxComponent and Store  - https://github.com/Workiva/w_flux/pull/35
 CP-940  - Update readmes to use/reference dart_dev, w_flux  - https://github.com/Workiva/w_flux/pull/34

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/0.3.0...CP-794_release_1.0.0

### CODE REVIEW

**Comment by dustinlessard-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Comment by teresarevious-wf** [comment]
RM +1

**Pull request merged**
