### PR TITLE
CP-1432 Release w_flux 2.2.0

### PR DESCRIPTION
**Pull request by charliekump-wf**
JIRA: https://jira.webfilings.com/browse/CP-1432

Releases that need to go out at the same time (if any): 

JIRA and PR's included in this release: 

 CP-1598  - Widen react-dart version range to support 1.0.0, w_flux  - https://github.com/Workiva/w_flux/pull/56

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/2.1.0...CP-1432_release_2.2.0

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by greglittlefield-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
@jayudey-wf ready :ship:

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
