### PR TITLE
CP-854 Fix image link in README, w_flux

### PR DESCRIPTION
**Pull request by maxwellpeterson-wf**
## Issue

The image link in the README was broken
## Changes

**Source:**
- Update link to image
## Testing
- None, doc-only change

@trentgrover-wf 
@evanweible-wf 
@dustinlessard-wf 
FYI @jayudey-wf

### CODE REVIEW

**Comment by jayudey-wf** [comment]
@rosie run_merge_script

**Comment by jayudey-wf** [comment]
@rmconsole-wf

**Comment by travisreed-wf** [comment]
hmmm

**Comment by travisreed-wf** [comment]
added proper package

**Comment by travisreed-wf** [comment]
@rosie run_merge_script

**Pull request merged**
