### PR TITLE
CP-1188 Release w_flux 2.0.0

### PR DESCRIPTION
**Pull request by jayudey-wf**
JIRA: https://jira.webfilings.com/browse/CP-1188

JIRA and PR's included in this release: 

 CP-1192  - Store: switch to a default ctor and a transformer ctor  - https://github.com/Workiva/w_flux/pull/49

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_flux/compare/1.1.0...CP-1188_release_2.0.0

### CODE REVIEW

**Comment by trentgrover-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
